### ISSUE TITLE
Time tags are non standard

### ISSUE THREAD

**Issue by bjornua** [RusKursusGruppen/beercalc#11]
Fix time html tags, so that they comply with the standard. Also, the time tag titles are all kinda unreadable now.

**Comment by bjornua** [comment]
Acutally, i'm confused if there even exists such a standard. One thing is for sure. The user representation could look nicer IMO

**Comment by degeberg** [comment]
I'm pretty sure that I validated all templates against the W3C validator. Anyways, the standard is here: http://www.whatwg.org/specs/web-apps/current-work/multipage/common-microsyntaxes.html#global-dates-and-times

**Comment by bjornua** [comment]
Aren't we forgetting timezones? Shouldn't we just always use zulu (utc) time
and add Z after?
